const fakeusers = [
  {
    id: 1,
    username: "jdoe",
    name: "John Doe",
    email: "john.doe@fake.com",
    phone: "1114567890",
    address: "1234 Main St",
    city: "Anytown",
    state: "CA",
    zip: "12345",
  },
  {
    id: 2,
    username: "mjane",
    name: "Marie Jane",
    email: "jane.marie@fake.com",
    phone: "1214567890",
    address: "Arlington St 1234",
    city: "London",
    state: "London",
    zip: "L4321",
  },
  {
    id: 3,
    username: "jsmith",
    name: "John Smith",
    email: "",
    phone: "131337890",
    address: "23 Rodeo Dr",
    city: "Los Angeles",
    state: "CA",
    zip: "34105",
  },
];
